<?= '<?php' ?>

/*
 * (c) Leonardo Brugnara
 *
 * Full copyright and license information in LICENSE file.
 *
 * -------------------------------------------------------
 *
 * WARNING: This is an autogenerated file, you should NOT edit this file as all
 *  the changes will be lost on file regeneration.
 *  If you want to add custom code to this class, consider using the GEN_TRAIT option
 *  to generate a Trait.
 *
 */

namespace <?= $model->namespace ?>\DataMappers;

use \Gekko\Database\MySQL\MySQLConnection;
use \Gekko\Database\MySQL\Mappers\MySQLDataMapper;

class <?= $model->className ?>DataMapper extends MySQLDataMapper
{
<?php foreach ($model->properties as $property): ?>
<?php endforeach; ?>

    public function __construct(MySQLConnection $connection)
    {
        parent::__construct($connection, (new \<?= $model->namespace . "\\Descriptors\\" . $model->className ?>Descriptor()));
    }
}
