<?= '<?php' ?>

/*
 * (c) Leonardo Brugnara
 *
 * Full copyright and license information in LICENSE file.
 *
 * -------------------------------------------------------
 *
 * WARNING: This is an autogenerated file, you should NOT edit this file as all
 *  the changes will be lost on file regeneration.
 *
 */

namespace <?= $model->namespace; ?>\Repositories;

use <?= $model->fullname() ?>;
use Gekko\Database\MySQL\MySQLConnection;
use <?= $model->namespace ?>\DataMappers\<?= $model->className ?>DataMapper;

trait <?= $model->className ?>RepositoryTrait
{
    /**
     * <?= $model->className ?> model data mapper
     *
     * @var <?= $model->namespace ?>\DataMappers\<?= $model->className ?>DataMapper
     */
    private $<?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper;

    public function __construct(MySQLConnection $connection)
    {
        $this-><?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper = new <?= $model->className ?>DataMapper($connection);
    }

    function get(...$id) : ?<?= $model->className ?>
    {
        return $this-><?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper->select(...$id);
    }

    function getAll() : array
    {
        return $this-><?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper->selectAll();
    }

    function add(<?= $model->className ?> $<?= strtolower($model->className[0]) . substr($model->className, 1) ?>) : bool
    {
        return $this-><?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper->insert($<?= strtolower($model->className[0]) . substr($model->className, 1) ?>);
    }

    function save(<?= $model->className ?> $<?= strtolower($model->className[0]) . substr($model->className, 1) ?>) : bool
    {
        return $this-><?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper->update($<?= strtolower($model->className[0]) . substr($model->className, 1) ?>);
    }

    function remove(<?= $model->className ?> $<?= strtolower($model->className[0]) . substr($model->className, 1) ?>) : bool
    {
        return $this-><?= strtolower($model->className[0]) . substr($model->className, 1) ?>DataMapper->delete($<?= strtolower($model->className[0]) . substr($model->className, 1) ?>);
    }
}
